---
title: "Geographic Join"
author: "Sarah"
date: "10/18/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(raster)
library(sp)
library(sf)
library(rgdal)
library(hsdar)
library(rgeos)
library(pdxTrees)
```

```{r}
# load polygon shapefiles
acpl <- st_read("~/Documents/Fall_2020_Reed/Thesis/tree_canopy/acpl_polygon.shp")
psme <- st_read("~/Documents/Fall_2020_Reed/Thesis/tree_canopy/psme_polygon.shp")
quru <- st_read("~/Documents/Fall_2020_Reed/Thesis/tree_canopy/quru_polygon.shp")
redcedar <- st_read("~/Documents/Fall_2020_Reed/Thesis/tree_canopy/redwood_polygon.shp")
segi <- st_read("~/Documents/Fall_2020_Reed/Thesis/tree_canopy/segi_polygon.shp")
acma <- st_read("~/Documents/Fall_2020_Reed/Thesis/tree_canopy/acma_polygon.shp")
grass <- st_read("~/Documents/Fall_2020_Reed/Thesis/tree_canopy/grass_polygon.shp")

# add polygon tree type column
acpl$id_type <- "acpl"
psme$id_type <- "psme"
quru$id_type <- "quru"
redcedar$id_type <- "redcedar"
segi$id_type <- "segi"
acma$id_type <- "acma"
grass$id_type <- "grass"

# combine polygon shapefiles
combined_poly <- rbind(acpl, psme, quru, redcedar, segi, acma, grass)

# create multipolygon object
multi_poly <- st_multipolygon(combined_poly$geometry)

# load point datasets
acpl_pts <- st_read("~/tree_imaging/shapefiles/acpl_shapefile.shp")
psme_pts <- st_read("~/tree_imaging/shapefiles/psme_shapefile.shp")
quru_pts <- st_read("~/tree_imaging/shapefiles/quru_shapefile.shp")
redcedar_pts <- st_read("~/tree_imaging/shapefiles/redcedar_shapefile.shp")
segi_pts <- st_read("~/tree_imaging/shapefiles/segi_shapefile.shp")
acma_pts <- st_read("~/tree_imaging/shapefiles/acma_shapefile.shp")

# combine point datasets
combined_pts <- rbind(acpl_pts, psme_pts, quru_pts, redcedar_pts, segi_pts, acma_pts)

# join combined points to combined polygons
poly_join <- st_join(combined_poly, combined_pts, largest = T)

# tidy polygon-point dataset
poly_join <- poly_join %>%
  mutate(id = c(1:nrow(poly_join)))
```

```{r}
# extract values and tidy function
names <- c("ID", "red", "green", "blue", "ir")
pixels_extraction <- function(stack, poly_df, id) {
  val <- raster::extract(stack, poly_df, df = TRUE)
  colnames(val) <- names
  val <- drop_na(val) %>%
    mutate(rstrip = id)
  return(val)
}
```

```{r}
# load raster layer object
stack_a <- stack("planet/20200902_184428_1005_3B_AnalyticMS_clip.tif")
stack_b <- stack("planet/20200902_184429_1005_3B_AnalyticMS_clip.tif")
stack_c <- stack("planet/20200902_183008_24_1065_3B_AnalyticMS_clip.tif")
stack_d <- stack("planet/20200902_183006_18_1065_3B_AnalyticMS_clip.tif")
stack_e <- stack("planet/20200902_184430_1005_3B_AnalyticMS_clip.tif")

# match raster project to polygons
raster_crs <- CRS(projection(stack_a))
poly_join_reprojected <- spTransform(as_Spatial(poly_join), raster_crs)
# saveRDS(poly_join_reprojected, "data/poly_join_reprojected.rds")

# extract pixel values from polygons into a dataframe
val_a <- pixels_extraction(stack_a, poly_join_reprojected, "a")
val_b <- pixels_extraction(stack_b, poly_join_reprojected, "b")
val_c <- pixels_extraction(stack_c, poly_join_reprojected, "c")
val_d <- pixels_extraction(stack_d, poly_join_reprojected, "d")
val_e <- pixels_extraction(stack_e, poly_join_reprojected, "e")

# semi_join returns rows of x where it can find a match in y
val_combined <- rbind(val_a, anti_join(val_b, val_a, by = "ID"))
val_combined <- rbind(val_combined, anti_join(val_c, val_combined, by = "ID"))
val_combined <- rbind(val_combined, anti_join(val_d, val_combined, by = "ID"))
val_combined <- rbind(val_combined, anti_join(val_e, val_combined, by = "ID"))

# tidy pixel table
pixels_data <-left_join(val_combined, poly_join_reprojected %>% rename(ID = id)) %>%
  mutate(ndvi = (ir - red)/(ir + red), 
         Cmmn_Nm = replace_na(as.character(Cmmn_Nm), "grass"),
         red_blue = red/blue,
         # ir_red = ir/red,
         red_green = red/green,
         blue_green = blue/green)
```


```{r}
# load single pixel tree points
pdxTrees_parks <- get_pdxTrees_parks()
pdxTrees_streets <- get_pdxTrees_streets()
pdxTrees_combined <- full_join(pdxTrees_parks, pdxTrees_streets)
trees_dat <- pdxTrees_combined %>%
  dplyr::filter(DBH >= 25, Common_Name %in% "Western Redcedar" | Species %in% unique(pixels_data$Species))

# convert to spatial points and reproject
coordinates(trees_dat) <- ~ Longitude + Latitude
proj4string(trees_dat)<- CRS("+proj=longlat +datum=WGS84")
trees_reprojected <- spTransform(trees_dat, raster_crs)

# extract pixels for all trees
pix_a <- pixels_extraction(stack_a, trees_reprojected, "a")
pix_b <- pixels_extraction(stack_b, trees_reprojected, "b")
pix_c <- pixels_extraction(stack_c, trees_reprojected, "c")
pix_d <- pixels_extraction(stack_d, trees_reprojected, "d")
pix_e <- pixels_extraction(stack_e, trees_reprojected, "e")

# semi_join returns rows of x where it can find a match in y
pix_combined <- rbind(pix_a, anti_join(pix_b, pix_a, by = "ID"))
pix_combined <- rbind(pix_combined, anti_join(pix_c, pix_combined, by = "ID"))
pix_combined <- rbind(pix_combined, anti_join(pix_d, pix_combined, by = "ID"))
pix_combined <- rbind(pix_combined, anti_join(pix_e, pix_combined, by = "ID"))

# tidy centers pixel table
pix_tree_center <- pix_combined %>%
  mutate(ID = as.character(ID)) %>%
  left_join(trees_reprojected@data, by = c("ID" = "UserID")) %>%
  mutate(ndvi = (ir - red)/(ir + red),
         red_blue = red/blue,
         # ir_red = ir/red,
         red_green = red/green,
         blue_green = blue/green,
         Cmmn_Nm = case_when(
           Common_Name %in% "Maple, Norway" ~ "Norway Maple",
           Common_Name %in% "Maple, Bigleaf" ~ "Bigleaf Maple",
           TRUE ~ as.character(Common_Name)
         )) %>%
  dplyr::filter(Cmmn_Nm %in% c("Western Redcedar", "Bigleaf Maple", "Douglas-Fir",
                        "Giant Sequoia", "Norway Maple"))
pix_tree_center %>%
  count(Cmmn_Nm)
pixels_data %>%
  count(Cmmn_Nm)
```

```{r}
# save results
# write.csv(poly_join_reprojected,'data/poly_join_reprojected1.csv', row.names = F)
# write.csv(val_combined,'data/val_combined1.csv', row.names = F)
# write.csv(pixels_data,'data/pixels_data.csv', row.names = F)
# write.csv(pix_tree_center,'data/pix_tree_center.csv', row.names = F)
```


