---
title: "Modelling"
author: "Sarah"
date: "2/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster)
library(caret)
library(tidyverse)
library(spdplyr)
library(doParallel)
library(pdxTrees)
library(sf)
library(tigris)
library(gridExtra)
library(RColorBrewer)
```

```{r}
# load masked raster images
stack_a <- stack("data/ndvi_mask_a.tif")
stack_b <- stack("data/ndvi_mask_b.tif")
stack_c <- stack("data/ndvi_mask_c.tif")
stack_d <- stack("data/ndvi_mask_d.tif")
stack_e <- stack("data/ndvi_mask_e.tif")

# load trained models
rf_small_grouped <- readRDS("data/rf_small_grouped.rds")
svm2_grouped <- readRDS("data/svm2_grouped.rds")
```

```{r}
# prep rasters function
predRaster <- function(stack) {
  stack <- stack(stack, ((stack[[4]] - stack[[1]])/(stack[[4]] + stack[[1]])),
                 (stack[[1]]/stack[[3]]), (stack[[4]]/stack[[1]]),
                 (stack[[1]]/stack[[2]]), (stack[[3]]/stack[[2]]))
  names(stack) <- c("red", "green", "blue", "ir", "ndvi", "red_blue", 
                    "ir_red", "red_green", "blue_green")
  cl <- makeCluster(3, type = "FORK")  
  registerDoParallel(cl)  
  results_RF <- raster::predict(stack, rf_small_grouped, progress = "text")
  results_SVM <- raster::predict(stack, svm2_grouped, progress = "text")
  results <- stack(results_RF, results_SVM)
  stopCluster(cl)
  return(results)
}

results_a <- predRaster(stack_a) # 41min
results_b <- predRaster(stack_b)
results_c <- predRaster(stack_c)
results_d <- predRaster(stack_d)
results_e <- predRaster(stack_e)

# save results
# writeRaster(results_a,"data/results_a.grd", format = "raster", overwrite = T)
# writeRaster(results_b,"data/results_b.grd", format = "raster", overwrite = T)
# writeRaster(results_c,"data/results_c.grd", format = "raster", overwrite = T)
# writeRaster(results_d,"data/results_d.grd", format = "raster", overwrite = T)
# writeRaster(results_e,"data/results_e.grd", format = "raster", overwrite = T)
```

Visualize results
```{r}
# load results
results_a <- stack("data/results_a.grd")
results_b <- stack("data/results_b.grd")
results_c <- stack("data/results_c.grd")
results_d <- stack("data/results_d.grd")
results_e <- stack("data/results_e.grd")

# RF rasters merged
r_list_RF <- list(results_a[[1]], results_b[[1]], results_c[[1]],
                  results_d[[1]], results_e[[1]])
m_RF <- do.call(merge, r_list_RF)
m_red <- m_RF == 5 # RF redcedars
m_grass <- m_RF == 4 # RF grass
m_seq <- m_RF == 3 # RF Giant Sequoia
m_fir <- m_RF == 2 # RF Douglas-Fir
m_broad <- m_RF == 1 # RF Broadleaf

# SVM rasters merged
r_list_red_SVM <- list(results_a[[2]], results_b[[2]], results_c[[2]],
                  results_d[[2]], results_e[[2]])
m_red_SVM <- do.call(merge, r_list_red_SVM)
m_red_SVM <- m_red_SVM == 5 # SVM redcedars


# compare rasters
r_matches <- m_red == m_red_SVM
freq(r_matches)[2, ]/(freq(r_matches)[2, ] + freq(r_matches)[1, ])
# (r_matches == 1)/((r_matches == 0) + (r_matches == 1)) percentage in common 91%


# load city outline
or_cities <- places("OR")
portland <- or_cities %>%
  dplyr::filter(NAME == "Portland")
portland_wgs84 <- spTransform(portland, 
                              CRS("+proj=utm +zone=10 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"))

# plot predictions
plot(m_red, main = "RF Western Redcedar Predictions", 
     labels = F, xaxt = 'n', yaxt = 'n', legend = F)
plot(portland_wgs84, add = T)

plot(m_red_SVM, main = "SVM Western Redcedar Predictions", 
     labels = F, xaxt = 'n', yaxt = 'n', legend = F)
plot(portland_wgs84, add = T)
```

Compare to pdxTrees
```{r}
# load street trees western redcedars
pdxTrees_parks <- get_pdxTrees_parks()
pdxTrees_streets <- get_pdxTrees_streets()

redcedar_dat_street <- pdxTrees_streets %>%
  filter(Common_Name %in% "Western Redcedar") %>%
  dplyr::select(Longitude, Latitude, Common_Name)
redcedar_dat_park <- pdxTrees_parks %>%
  filter(Common_Name %in% "Western Redcedar") %>%
  dplyr::select(Longitude, Latitude, Common_Name)
redcedar_dat <- rbind(redcedar_dat_street, redcedar_dat_park)

# match coordinate reference system
coordinates(redcedar_dat) <- c("Longitude", "Latitude")
proj4string(redcedar_dat) <- CRS("+init=epsg:4326")
dat_transformed <- spTransform(redcedar_dat, CRS("+proj=utm +zone=10 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"))


# plot pdxTrees with predictions
plot(m_red, main = "RF C = 5 with pdxTrees", 
     labels = F, xaxt = 'n', yaxt = 'n', legend = F, col = "darkgreen")
plot(dat_transformed, col = rgb(red = 0.2, green = 0.2, blue = 1.0, alpha = 0.2), cex = .2, add = T)
plot(portland_wgs84, add = T)

plot(m_red_SVM, main = "SVM C = 5 with pdxTrees", 
     labels = F, xaxt = 'n', yaxt = 'n', legend = F, col = "darkgreen")
plot(dat_transformed, col = rgb(red = 0.2, green = 0.2, blue = 1.0, alpha = 0.2), cex = .2, add = T)
plot(portland_wgs84, add = T)

# match pixels with pdxTrees to test for accuracy
street_mask_rf <- mask(m_red, dat_transformed)
street_mask_svm <- mask(m_red_SVM, dat_transformed)
freq(street_mask_rf)[1, 2]/nrow(dat_transformed) # testing accuracy estimates for Western redcedars
# 57%
freq(street_mask_svm)[1, 2]/nrow(dat_transformed) # testing accuracy estimates for Western redcedars
# 63%

# smaller visualization around Reed
reed_stack <- crop(m_red, extent(528000, 529500, 5035500, 5036800))
trees_reed <- crop(dat_transformed, extent(528000, 529500, 5035500, 5036800))
reed <- crop(m_RF, extent(528000, 529500, 5035500, 5036800))

# Portland with extent box
plot(m_red, main = "RF C = 5 with pdxTrees", 
     xaxt = 'n', yaxt = 'n', legend = F)
plot(dat_transformed, col = rgb(red = 0.2, green = 0.2, blue = 1.0, alpha = 0.6), cex = .2, add = T, pch = 1)
plot(portland_wgs84, add = T)
plot(extent(reed_stack), add = T, col = "maroon")

# Reed plot
plot(reed_stack, main = "", labels = F, xaxt = 'n', yaxt = 'n', legend = F)
plot(trees_reed, col = rgb(red = 0.2, green = 0.2, blue = 1.0, alpha = 1), cex = .2, add = T, pch = 1)
plot(extent(reed_stack), add = T, col = "maroon")

r_points <- rasterToPoints(reed)
r_df <- data.frame(r_points) %>%
  mutate(layer = case_when(
    layer == 1 ~ "Broadleaf",
    layer == 2 ~ "Douglas-Fir",
    layer == 3 ~ "Giant Sequoia",
    layer == 4 ~ "Grass",
    layer == 5 ~ "Western Redcedar"))

m_red <- m_RF == 5 # RF redcedars
m_grass <- m_RF == 4 # RF grass
m_seq <- m_RF == 3 # RF Giant Sequoia
m_fir <- m_RF == 2 # RF Douglas-Fir
m_broad <- m_RF == 1 # RF Broadleaf
ggplot(data = r_df) + 
  geom_tile(aes(x, y, fill = layer), alpha = 0.98) + 
  scale_fill_viridis_d() +
  coord_equal() +
  theme_minimal() +
  theme(panel.grid.major = element_blank()) +
  xlab("") + ylab("")
```

Sources:
https://mgimond.github.io/Spatial/mapping-data-in-r.html
https://www.r-bloggers.com/2020/05/threading-and-caret-burning-your-cpu-to-improve-model-training-speed/
http://amsantac.co/blog/en/2015/11/28/classification-r.html
https://geoscripting-wur.github.io/AdvancedRasterAnalysis/