---
title: "Untitled"
author: "Sarah"
date: "11/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(sf)
library(raster)
library(rgdal)
library(tigris)
library(spdplyr)
```

```{r}
# load city boundary shapefile
or_cities <- places("OR")
portland <- or_cities %>%
  filter(NAME == "Portland")
```

```{r}
# load raster layer object
stack_a <- stack("planet/20200902_184428_1005_3B_AnalyticMS_clip.tif")
stack_b <- stack("planet/20200902_184429_1005_3B_AnalyticMS_clip.tif")
stack_c <- stack("planet/20200902_183008_24_1065_3B_AnalyticMS_clip.tif")
stack_d <- stack("planet/20200902_183006_18_1065_3B_AnalyticMS_clip.tif")
stack_e <- stack("planet/20200902_184430_1005_3B_AnalyticMS_clip.tif")

## crop and mask pixels outside portland
stack_a <- crop(mask(stack_a, spTransform(portland, crs(stack_a))), extent(portland))
stack_b <- crop(mask(stack_b, spTransform(portland, crs(stack_b))), extent(portland))
stack_c <- crop(mask(stack_c, spTransform(portland, crs(stack_c))), extent(portland))
stack_d <- crop(mask(stack_d, spTransform(portland, crs(stack_d))), extent(portland))
stack_e <- crop(mask(stack_e, spTransform(portland, crs(stack_e))), extent(portland))

# ndvi mask remove values below 0
ndvi_a <- (stack_a[[4]] - stack_a[[1]]) / (stack_a[[4]] + stack_a[[1]])
ndvi_b <- (stack_b[[4]] - stack_b[[1]]) / (stack_b[[4]] + stack_b[[1]])
ndvi_c <- (stack_c[[4]] - stack_c[[1]]) / (stack_c[[4]] + stack_c[[1]])
ndvi_d <- (stack_d[[4]] - stack_d[[1]]) / (stack_d[[4]] + stack_d[[1]])
ndvi_e <- (stack_e[[4]] - stack_e[[1]]) / (stack_e[[4]] + stack_e[[1]])

plot(ndvi_a, main = "NDVI", axes = FALSE, box = FALSE)

# masked ndvi values
ndvi_a[ndvi_a < 0] <- NA
ndvi_b[ndvi_b < 0] <- NA
ndvi_c[ndvi_c < 0] <- NA
ndvi_d[ndvi_d < 0] <- NA
ndvi_e[ndvi_e < 0] <- NA

ndvi_mask_a <- mask(stack_a, ndvi_a, filename = "data/ndvi_mask_a.tif", overwrite = T)
ndvi_mask_b <- mask(stack_b, ndvi_b, filename = "data/ndvi_mask_b.tif", overwrite = T)
ndvi_mask_c <- mask(stack_c, ndvi_c, filename = "data/ndvi_mask_c.tif", overwrite = T)
ndvi_mask_d <- mask(stack_d, ndvi_d, filename = "data/ndvi_mask_d.tif", overwrite = T)
ndvi_mask_e <- mask(stack_e, ndvi_e, filename = "data/ndvi_mask_e.tif", overwrite = T)
```

```{r}
stack_a <- stack("data/ndvi_mask_a.tif")
stack_b <- stack("data/ndvi_mask_b.tif")
stack_c <- stack("data/ndvi_mask_c.tif")
stack_d <- stack("data/ndvi_mask_d.tif")
stack_e <- stack("data/ndvi_mask_e.tif")

# Grass Index  = (ir + red + blue + green)/4
gi_a <- (stack_a[[1]] + stack_a[[2]] + stack_a[[3]] + stack_a[[4]])/4
gi_b <- (stack_b[[1]] + stack_b[[2]] + stack_b[[3]] + stack_b[[4]])/4
gi_c <- (stack_c[[1]] + stack_c[[2]] + stack_c[[3]] + stack_c[[4]])/4
gi_d <- (stack_d[[1]] + stack_d[[2]] + stack_d[[3]] + stack_d[[4]])/4
gi_e <- (stack_e[[1]] + stack_e[[2]] + stack_e[[3]] + stack_e[[4]])/4

# remove values above 4900**
gi_a[gi_a > 4900] <- NA
gi_b[gi_b > 4900] <- NA
gi_c[gi_c > 4900] <- NA
gi_d[gi_d > 4900] <- NA
gi_e[gi_e > 4900] <- NA

gi_mask_a <- mask(stack_a, gi_a, filename = "data/grass_mask_a.tif", overwrite = T)
gi_mask_b <- mask(stack_b, gi_b, filename = "data/rass_mask_b.tif", overwrite = T)
gi_mask_c <- mask(stack_c, gi_c, filename = "data/grass_mask_c.tif", overwrite = T)
gi_mask_d <- mask(stack_d, gi_d, filename = "data/grass_mask_d.tif", overwrite = T)
gi_mask_e <- mask(stack_e, gi_e, filename = "data/grass_mask_e.tif", overwrite = T)

plotRGB(gi_mask_a, main = "ndvi and grass mask", axes = FALSE, box = FALSE)

?writeRaster
# save as geotif
```

```{r}
# look at ndvi/grass values from pixels dataset to determine threshold
pixels_data <- read.csv('data/pixels_data.csv')

ggplot(pixels_data, mapping = aes(x = ndvi)) +
  geom_histogram(alpha = 0.6, fill = "blue") +
  geom_vline(xintercept = 0.0) +
  theme_minimal()

ggplot(pixels_data, mapping = aes(x = (ir + red + blue + green), fill = Cmmn_Nm)) +
  geom_density(alpha = 0.6) +
  scale_fill_viridis_d() + theme_minimal()

ggplot(pixels_data %>% filter(Cmmn_Nm %in% "grass"), mapping = aes(x = ndvi, fill = Cmmn_Nm)) +
  geom_density(alpha = 0.6) +
  scale_fill_viridis_d() + theme_minimal()

ggplot(pixels_data, mapping = aes(x = ir/green, y = ir, color = Cmmn_Nm)) +
  geom_point(alpha = 0.6) +
  scale_colour_viridis_d()

ggplot(pixels_data%>% filter(Cmmn_Nm %in% "grass"), mapping = aes(x = ir - red, y = ir + red, color = Cmmn_Nm)) +
  geom_point(alpha = 0.6) +
  scale_colour_viridis_d()

brightness <- (ir + red + blue + green)/4

# masking out ndvi values below 0 (halfway up first peak) to keep vegetation pixels
# and mask out grass values above __ to remove grass pixels
```

```{r}
# Green Leaf Index (GLI) = [(green - red) + (green - blue)] / (2*green) + red + blue
gli_a <- ((stack_a[[2]] - stack_a[[1]]) + (stack_a[[2]] - stack_a[[3]]))/ (2*stack_a[[2]] + stack_a[[1]] + stack_a[[3]])
plot(gli_a, main = "GLI", axes = FALSE, box = FALSE)
```

```{r}
# Enhanced Vegetation Index (EVI) = 2.5*(nir - red)/(nir + 6*red - 7.5*blue + 1)
evi_a <- 2.5*(stack_a[[4]] - stack_a[[1]])/(stack_a[[4]] + 6*stack_a[[1]] - 7.5*stack_a[[3]])
plot(evi_a, main = "EVI", axes = FALSE, box = FALSE)
```


https://www.rdocumentation.org/packages/raster/versions/3.4-5/topics/mask