---
title: "Pixels Exploratory Analysis"
author: "Sarah"
date: "11/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(corrplot)
```

```{r}
# load data
pixels_data <- read.csv('data/pixels_data.csv')
```

```{r}
# counts analysis
pixels_data %>%
  group_by(Cmmn_Nm) %>%
  summarise(counts = n())

pixels_data %>%
  count(id_type)

n_distinct(pixels_data)

# group by number of polygons per tree class per strip
poly_count <- pixels_data %>%
  group_by("Raster Strip" = rstrip, "Tree Name" = Cmmn_Nm) %>%
  count("Polygons" = length(unique(ID)))
```

```{r}
# preprocess pca
train_pca <- preProcess(dplyr::select(train, -Cmmn_Nm), method = c("center", "scale", "pca"))
train_pca
train_pca$method
train_pca$rotation

# look at correlation matrix to select predictors
corr_matrix <- round(cor(train %>% ungroup() %>% dplyr::select(-Cmmn_Nm)), 2)
corrplot(corr_matrix, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)
```


```{r}
# distributions across bands
ggplot(pixels_data) +
  geom_density(aes(x = red), col = "red") +
  geom_density(aes(x = blue), col = "blue") + 
  geom_density(aes(x = green), col = "green") + 
  geom_density(aes(x = ir), col = "purple") + 
  facet_wrap(~Cmmn_Nm)+
  theme_classic() + labs(x = "values")

# how bands correlate with each other
bands <- pixels_data %>%
  dplyr::select(blue, green, red, ir)
library(corrplot)
corrplot(cor(bands))
corrplot(cor(bands), method = "number")
```

```{r}
# different species in each band
pixels_data %>%
  group_by(Cmmn_Nm) %>%
  summarise(count = n(), ave_blue = mean(blue), ave_red = mean(red), 
            ave_green = mean(green), ave_ir = mean(ir))

library(reshape2)
pixels_filtered <- pixels_data %>%
  dplyr::select(red, green, blue, ir, Cmmn_Nm)
pixels_long <- melt(pixels_filtered, id.vars=c("Cmmn_Nm"))

ggplot(pixels_long, aes(x = Cmmn_Nm, y = value)) +
  geom_boxplot() + facet_wrap(~variable) + theme_classic() +
  theme(axis.text.x = element_text(angle = 90))

ggplot(pixels_long, aes(x = Cmmn_Nm, y = value)) +
  geom_violin() + facet_wrap(~variable) + theme_classic() +
  theme(axis.text.x = element_text(angle = 90))

ggplot(pixels_data, aes(x = Cmmn_Nm, y = ndvi)) +
  geom_violin() + theme_classic() +
  theme(axis.text.x = element_text(angle = 90))
```

```{r}
# red v. ir analysis
ggplot(pixels_data, mapping = aes(x = red, y = ir, color = Cmmn_Nm)) +
  geom_point(alpha = 0.6) +
  scale_colour_viridis_d()

ggplot(pixels_data, mapping = aes(x = red - ir, y = blue - green, color = Cmmn_Nm)) +
  geom_point(alpha = 0.6) +
  scale_colour_viridis_d()

# ndvi values
ggplot(pixels_data, aes(x = ndvi)) +
  geom_density()
ggplot(pixels_data, aes(x = ndvi)) +
  geom_histogram(fill = "turquoise") +
  theme_minimal() + labs(x = "NDVI values", y = "frequency")

av_nir <- mean(pixels_data$ir)
av_green <- mean(pixels_data$green)
av_blue <- mean(pixels_data$blue)
av_red <- mean(pixels_data$red)
```

NDVI formula:
$$NDVI = \frac{NIR - Red}{NIR + Red}$$
References: 
https://geocompr.robinlovelace.net/spatial-operations.html#spatial-ras
https://www.earthdatascience.org/courses/earth-analytics/multispectral-remote-sensing-data/vegetation-indices-NDVI-in-R/
https://ourcodingclub.github.io/tutorials/spatial/#section2

```{r}
# condition of trees
pixels_data %>%
  group_by(Conditn, Cmmn_Nm) %>%
  summarise(count = n())

ggplot(pixels_data, aes(x = Cmmn_Nm, y = Cr_W_NS, fill = Conditn)) +
  geom_col(position = "fill")

ggplot(pixels_data, aes(x = Conditn, y = red, fill = Cmmn_Nm)) +
  geom_col()

# for a species, different combinations of bands, color coded by condition
# blue - green, boxplot for given species
ggplot(pixels_data, aes(x = Conditn, y = ndvi, fill = Cmmn_Nm)) +
  geom_violin() + theme_classic() +
  theme(axis.text.x = element_text(angle = 90))

ggplot(pixels_data, aes(x = Conditn, y = red, fill = Cmmn_Nm)) +
  geom_violin() + theme_classic() +
  theme(axis.text.x = element_text(angle = 90))

ggplot(pixels_data, aes(x = Conditn, y = blue, fill = Cmmn_Nm)) +
  geom_violin() + theme_classic() +
  theme(axis.text.x = element_text(angle = 90))

ggplot(pixels_data, aes(x = Conditn, y = green, fill = Cmmn_Nm)) +
  geom_violin() + theme_classic() +
  theme(axis.text.x = element_text(angle = 90))
```


```{r}
# create table of polygons per raster strip
poly_count <- pixels_data %>%
  group_by("Raster Strip" = rstrip, "Common Name" = Cmmn_Nm) %>%
  count("Polygons" = length(unique(ID)))

# create table of polygons per raster strip per tree species
poly_totals <- pixels_data %>%
  group_by("Raster Strip" = rstrip) %>%
  count("Polygons" = length(unique(ID)))
```

